site_name: Ed-AISys Group
theme:
  name: material
  features:
    - content.code.copy
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    # - search.suggest
    - toc.follow
    # - toc.integrate

nav:
  - 'Home': 'index.md'
  - 'Must Read!': 'important.md'
  - 'Cluster Summary': 'servers/summary.md'
  - 'Cluster Info': 
    - 'Proxy': 'servers/azure.md'
    - 'Gala': 'servers/gala.md'
    - 'Jazz': 'servers/jazz.md'
  - 'User Management': 'manual/user.md'

plugins:
  - search: {}
  - encryptcontent:
      global_password: 'awesomeDAISys!'
      title_prefix: ''
      encryption_info_message: 'Contact Ed-AISys Group Member for password'
      search_index: 'dynamically'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
